apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: uptime-kuma-backendconfig
  namespace: uptime-kuma
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3001
    type: HTTP
    requestPath: /dashboard
